export const ApiPaths = {
  COLUMNS: '/columns',
  DATABASES: '/databases',
  DATABASE_EXPORT: '/database/export',
  DATABASE_EXPORT_TABLES: '/database/export-tables',
  DATABASE_IMPORT: '/database/import',
  DATABASE_IMPORT_FILE: '/database/import/file',
  TABLES: '/tables',
  TABLES_DDL: '/tables/ddl',
  TABLE_DATA: '/table-data/table',
  VIEWS: '/views',
  VIEWS_DDL: '/views/ddl',
  VIEW_DATA: '/table-data/view',
  FUNCTIONS: '/functions',
  FUNCTIONS_DDL: '/functions/ddl',
  PROCEDURES: '/procedures',
  PROCEDURES_DDL: '/procedures/ddl',
  TRIGGERS: '/triggers',
  TRIGGERS_DDL: '/triggers/ddl',
  INDEXES: '/indexes',
  PRIMARY_KEYS: '/primary-keys',
} as const;
